# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: badc7b60d512fbb9273127eec99474f70c95aedcf490d07facb2ce8f62a2834399792c9f065b35b3183915a60789856f96ed753c35bb9c4625810b73ad20851c

test:
  secret_key_base: 5c1555f0f3d6e09bcde8ff3e8d8850f2d0378d668d9f23b5805a3541f92c910b5c779c5377e0896989c48d567fa49fa82172145f6d1ee9faf71b6ecc33a491c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
